name: Build Project

on:
  workflow_call:
    outputs:
      build_output_path:
        description: "Path to the build output directory"
        value: ${{ jobs.build.outputs.build_output_path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_output_path: ${{ steps.build-app.outputs.build_output_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Build app
        id: build-app
        run: |
          npm run build
          echo "build_output_path=$(pwd)/dist" >> $GITHUB_OUTPUT
