# .github/workflows/build.yaml
name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      build_target:
        required: true
        type: string
    outputs:
      build_output_path:
        description: "Path to build output"
        value: ${{ jobs.build.outputs.build_output_path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_output_path: ${{ steps.build-step.outputs.build_output_path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Using v4 as it's current

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        id: build-step
        run: |
          npm run build
          echo "build_output_path=build/" >> $GITHUB_OUTPUT # Assuming standard React build output folder
