name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Trigger on direct pushes to the main branch
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore: # Optional: Ignore changes to specific files/folders that shouldn't trigger a deploy
      - "README.md"
      - "docs/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install # Or yarn install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch where your site will be deployed
          folder: dist # The output directory of your build
          repository-name: ${{ github.repository }} # Automatically gets your repository name
          user-name: ${{ github.event.inputs.user_name || github.event.repository_owner }}
          user-email: ${{ github.event.inputs.user_email || '${{ github.event.repository_owner }}@users.noreply.github.com' }}
