name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # or your main branch name
  merge:
    branches: -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder where your production build is located (usually 'build')
          branch: gh-pages # The branch to deploy to (gh-pages is common for GitHub Pages)
          token: ${{ secrets.GITHUB_TOKEN }}
